// SPDX-License-Identifier: CC0-1.0
pragma solidity ^0.8.24;

import {ACDFBase} from "./ACDFBase.t.sol";
import {ACDFTypes as T} from "../assets/erc-acdf/contracts/ACDFTypes.sol";
import {ACDFRegistry} from "../assets/erc-acdf/contracts/ACDFRegistry.sol";
import {IACDFPolicyRegistry} from "../assets/erc-acdf/contracts/interfaces/IACDFPolicyRegistry.sol";
import {IACDFRegistry} from "../assets/erc-acdf/contracts/interfaces/IACDFRegistry.sol";

/// Cross-language vectors (assets/erc-acdf/vectors/*.json, generated by tools/vectors.js with
/// ethers v6) re-derived here with solc. If encoding, hashing or the tally/composition rules
/// drift between implementations, these fail.
contract ACDFVectorsTest is ACDFBase {
    string constant DIR = "assets/erc-acdf/vectors/";

    function addr(uint160 i) internal pure returns (address) { return address(i); }

    function rosterOf(uint160[] memory ids, uint32 k, uint64 window, T.Acceptance acc) internal pure returns (T.BodySpec memory b) {
        b.kind = T.BodyKind.ROSTER_KOFN; b.acceptance = acc; b.k = k; b.window = window;
        b.members = new address[](ids.length);
        for (uint256 i = 0; i < ids.length; i++) b.members[i] = addr(ids[i]);
    }

    function ids(uint160 a, uint160 b) internal pure returns (uint160[] memory r) { r = new uint160[](2); r[0] = a; r[1] = b; }
    function ids(uint160 a, uint160 b, uint160 c) internal pure returns (uint160[] memory r) { r = new uint160[](3); r[0] = a; r[1] = b; r[2] = c; }
    function ids(uint160 a, uint160 b, uint160 c, uint160 d, uint160 e) internal pure returns (uint160[] memory r) {
        r = new uint160[](5); r[0] = a; r[1] = b; r[2] = c; r[3] = d; r[4] = e;
    }

    function vectorSpec(T.BodySpec[] memory bodies, T.Node[] memory nodes, string memory family) internal pure returns (T.PolicySpec memory s) {
        s.family = keccak256(bytes(family));
        s.version = 1;
        s.previous = bytes32(0);
        s.updateAuthority = addr(0xA07);
        s.bodies = bodies; s.nodes = nodes;
        s.maxAppeals = 0; s.appealWindow = 0; s.appealable = 0;
        s.appealStanding = T.AppealStanding.ANYONE;
        s.maxTotalDuration = 30 days; s.ackWindow = 0; s.allowAdvisory = false;
        s.descriptorHash = keccak256("descriptor");
    }

    // ---------------------------------------------------------------- policy ids

    function test_policy_id_vectors_match_ethers_encoding() public view {
        string memory json = vm.readFile(string.concat(DIR, "policy-id.json"));
        assertEq(vm.parseJsonUint(json, ".count"), 3);

        // vector 0: minimal 3-of-5
        T.BodySpec[] memory b1 = new T.BodySpec[](1);
        b1[0] = rosterOf(ids(1, 2, 3, 4, 5), 3, 1 days, T.Acceptance.ON_CHAIN_TALLY);
        T.Node[] memory n1 = new T.Node[](1); n1[0] = bodyNode(0);
        assertEq(pol.policyIdOf(vectorSpec(b1, n1, "vector.minimal")), vm.parseJsonBytes32(json, ".vectors[0].policyId"), "minimal-3of5");

        // vector 1: two-chamber ALL
        T.BodySpec[] memory b2 = new T.BodySpec[](2);
        b2[0] = rosterOf(ids(1, 2, 3), 2, 1 days, T.Acceptance.ON_CHAIN_TALLY);
        b2[1] = rosterOf(ids(3, 4, 5), 2, 1 days, T.Acceptance.ON_CHAIN_TALLY);
        T.Node[] memory n2 = new T.Node[](3);
        n2[0] = combNode(T.Combinator.ALL, 0, u32(1, 2)); n2[1] = bodyNode(0); n2[2] = bodyNode(1);
        assertEq(pol.policyIdOf(vectorSpec(b2, n2, "vector.two-chamber")), vm.parseJsonBytes32(json, ".vectors[1].policyId"), "two-chamber-all");

        // vector 2: veto over ALL with one appeal
        T.BodySpec[] memory b3 = new T.BodySpec[](3);
        b3[0] = rosterOf(ids(4, 5), 1, 12 hours, T.Acceptance.ON_CHAIN_TALLY);
        b3[1] = rosterOf(ids(1, 2, 3), 2, 2 days, T.Acceptance.SIGNED_BALLOTS);
        b3[2] = rosterOf(ids(3, 4, 5), 2, 3 days, T.Acceptance.ON_CHAIN_TALLY);
        T.Node[] memory n3 = new T.Node[](4);
        n3[0] = vetoNode(1, 0, T.VetoSilence.PASS_THROUGH);
        n3[1] = combNode(T.Combinator.ALL, 0, u32(2, 3)); n3[2] = bodyNode(1); n3[3] = bodyNode(2);
        T.PolicySpec memory s3 = vectorSpec(b3, n3, "vector.veto");
        s3.maxAppeals = 1; s3.appealWindow = 2 days; s3.appealable = 3; s3.maxTotalDuration = 10 days;
        assertEq(pol.policyIdOf(s3), vm.parseJsonBytes32(json, ".vectors[2].policyId"), "veto-over-all-with-appeal");
    }

    // ---------------------------------------------------------------- ERC-165 ids

    function test_interface_id_vectors() public view {
        string memory json = vm.readFile(string.concat(DIR, "interface-ids.json"));
        bytes memory a = vm.parseJsonBytes(json, ".ids.IACDFPolicyRegistry");
        bytes memory b = vm.parseJsonBytes(json, ".ids.IACDFRegistry");
        assertEq(bytes4(a), type(IACDFPolicyRegistry).interfaceId, "IACDFPolicyRegistry");
        assertEq(bytes4(b), type(IACDFRegistry).interfaceId, "IACDFRegistry");
        assertEq(a.length, 4); assertEq(b.length, 4);
    }

    // ---------------------------------------------------------------- EIP-712 digests

    function test_ballot_digest_vectors_match_ethers_typed_data() public {
        string memory json = vm.readFile(string.concat(DIR, "ballot-digest.json"));
        address fixedAddr = vm.parseJsonAddress(json, ".domain.verifyingContract");
        uint256 chainId = vm.parseJsonUint(json, ".domain.chainId");
        vm.chainId(chainId);
        vm.etch(fixedAddr, address(reg).code); // same code at the vector's verifyingContract
        ACDFRegistry fixedReg = ACDFRegistry(fixedAddr);
        uint256 n = vm.parseJsonUint(json, ".count");
        for (uint256 i = 0; i < n; i++) {
            string memory p = string.concat(".vectors[", vm.toString(i), "]");
            bytes32 digest = fixedReg.ballotDigest(
                vm.parseJsonBytes32(json, string.concat(p, ".issueId")),
                uint32(vm.parseJsonUint(json, string.concat(p, ".round"))),
                uint32(vm.parseJsonUint(json, string.concat(p, ".body"))),
                vm.parseJsonAddress(json, string.concat(p, ".voter")),
                vm.parseJsonBool(json, string.concat(p, ".approve"))
            );
            assertEq(digest, vm.parseJsonBytes32(json, string.concat(p, ".digest")), p);
        }
    }

    // ---------------------------------------------------------------- K-of-N truth table

    function statusOf(string memory s) internal pure returns (T.NodeStatus) {
        bytes32 h = keccak256(bytes(s));
        if (h == keccak256("Yes")) return T.NodeStatus.Yes;
        if (h == keccak256("No")) return T.NodeStatus.No;
        if (h == keccak256("Pending")) return T.NodeStatus.Pending;
        return T.NodeStatus.NoDecision;
    }

    function test_kofn_tally_vectors() public {
        string memory json = vm.readFile(string.concat(DIR, "kofn-tally.json"));
        uint256 n = vm.parseJsonUint(json, ".count");
        for (uint256 i = 0; i < n; i++) {
            string memory p = string.concat(".vectors[", vm.toString(i), "]");
            uint256 N = vm.parseJsonUint(json, string.concat(p, ".n"));
            uint32 K = uint32(vm.parseJsonUint(json, string.concat(p, ".k")));
            uint256 yes = vm.parseJsonUint(json, string.concat(p, ".yes"));
            uint256 no = vm.parseJsonUint(json, string.concat(p, ".no"));
            bool closed = vm.parseJsonBool(json, string.concat(p, ".closed"));
            T.NodeStatus expected = statusOf(vm.parseJsonString(json, string.concat(p, ".expected")));

            T.PolicySpec memory s = minimalSpec(N, K, 1 hours);
            s.family = keccak256(abi.encode("kofn-vector", i));
            bytes32 pid = register(s);
            bytes32 id = fileAsConsumer(pid, i + 1);
            for (uint256 v = 0; v < no; v++) vote(id, 0, v, false);
            for (uint256 v = 0; v < yes; v++) vote(id, 0, no + v, true);
            if (closed) vm.warp(vm.getBlockTimestamp() + 1 hours + 1);
            (T.NodeStatus st,,) = reg.bodyStatus(id, 1, 0);
            assertEq(uint8(st), uint8(expected), p);
        }
    }

    // ---------------------------------------------------------------- composition truth table

    function test_composition_vectors() public {
        string memory json = vm.readFile(string.concat(DIR, "composition.json"));
        uint256 n = vm.parseJsonUint(json, ".count");
        uint256[3] memory seats = [uint256(0), 2, 4]; // three disjoint 1-of-1 chambers
        for (uint256 i = 0; i < n; i++) {
            string memory p = string.concat(".vectors[", vm.toString(i), "]");
            string memory op = vm.parseJsonString(json, string.concat(p, ".op"));
            T.NodeStatus expected = statusOf(vm.parseJsonString(json, string.concat(p, ".expected")));
            string[3] memory ch;
            for (uint256 c = 0; c < 3; c++) ch[c] = vm.parseJsonString(json, string.concat(p, ".children[", vm.toString(c), "]"));

            T.BodySpec[] memory bodies = new T.BodySpec[](3);
            for (uint256 c = 0; c < 3; c++) {
                bodies[c].kind = T.BodyKind.ROSTER_KOFN;
                bodies[c].acceptance = T.Acceptance.ON_CHAIN_TALLY;
                bodies[c].members = new address[](1);
                bodies[c].members[0] = members[seats[c]];
                bodies[c].k = 1;
                // a child meant to be NoDecision gets a short window; the others stay open
                bodies[c].window = keccak256(bytes(ch[c])) == keccak256("D") ? 1 hours : 1 days;
            }
            T.Node[] memory nodes = new T.Node[](4);
            bytes32 oph = keccak256(bytes(op));
            if (oph == keccak256("ALL")) nodes[0] = combNode(T.Combinator.ALL, 0, u32(1, 2, 3));
            else if (oph == keccak256("ANY")) nodes[0] = combNode(T.Combinator.ANY, 0, u32(1, 2, 3));
            else nodes[0] = combNode(T.Combinator.KOFM, 2, u32(1, 2, 3));
            nodes[1] = bodyNode(0); nodes[2] = bodyNode(1); nodes[3] = bodyNode(2);
            T.PolicySpec memory s = spec(bodies, nodes, keccak256(abi.encode("composition-vector", i)));
            bytes32 pid = register(s);
            bytes32 id = fileAsConsumer(pid, i + 1);
            for (uint256 c = 0; c < 3; c++) {
                bytes32 v = keccak256(bytes(ch[c]));
                if (v == keccak256("Y")) vote(id, uint32(c), seats[c], true);
                else if (v == keccak256("N")) vote(id, uint32(c), seats[c], false);
            }
            vm.warp(vm.getBlockTimestamp() + 1 hours + 1); // closes the 1-hour windows only
            (T.NodeStatus st,,) = reg.nodeStatus(id, 1, 0);
            assertEq(uint8(st), uint8(expected), p);
        }
    }
}
